### ISSUE TITLE
TMCM-0960-MotionPy initialization error for TMCL-IDE

### ISSUE THREAD

**Issue by NavadeepGaneshU** [trinamic/PyTrinamicMicro#2]
Hi, 
I am trying to use TMCM-0960-MotionPy Kit with TMCL-IDE and pairing with PD42-1270 via CAN interface. First of all, the board initially came with boot.py, main.py and driver file. I installed the driver and the board isn't detected recognised in TMCL-IDE(though COM port is shown, but not connecting). I realized about preparing the board to run MicroPython after reading https://github.com/trinamic/PyTrinamicMicro/blob/master/GUIDE.MD and trying  "General" section of it. 
Till step 4, things worked well and I used command "python install.py C:\" as Python 3.9 is in C:\ drive for me. After, I copied main.py and boot.py to the E:\ which is root of TMCM-0960-MotionPy hardware(with SD card attached). After while opening Putty and accessing the serial port, its throwing error "no module named logging" and still the board is not recognised in TMCL-IDE. 
Did I follow the procedure properly? It's quite unclear for me, could you please explain the steps briefly? Any assistance would be of great help. Thanks. 

I have attached screenshots for reference:
![Screenshot (1099)](https://user-images.githubusercontent.com/52508011/117690667-b9038500-b1d8-11eb-8d4d-1742b4ea70c5.png)

![Screenshot (1096)](https://user-images.githubusercontent.com/52508011/117691004-0da70000-b1d9-11eb-9d37-171c11100b30.png)

@Lionheart1810  @trinamic-ed  @JonaHammer

**Comment by Lionheart1810** [comment]
The directory argument for the install script should actually be the **target** directory, where you want the files to be installed to.
It is **not** necessarily the disk on which Python is installed. I have updated the guide to clear up this misunderstanding.

You might just have installed this library to your C-Drive. The directory path "E:\" is just mentioned as an example, it can be any path really. You most likely want to install it to the mounted MotionPy-SD-Card, so you have to use the path to the root of that.

When you have recursively pulled this project with the suggested command, it should also install the now missing libraries for logging. But keep in mind that the installer does not install incrementally, so you might have to set the `-c` flag to automatically clear the installation before.

Also when you want to use the MotionPy as a Slave via USB, keep in mind that you have to close the corresponding COM-Port connection from PuTTY, so that TMCL-IDE can use it.

**Comment by NavadeepGaneshU** [comment]
Cool, okay! Thanks for clarifying those. I now successfully installed those to MotionPy SD card. I have copied boot.py and main.py from H:\PyTrinamicMicro\platforms\motionpy to H:\ which is the root of MotionPy. Board is not recognized by TMCL-IDE and in the Putty, it's still throwing some error saying "cant convert none type to string" and a couple of more in main.py and MotionPy.py. Also, going to one of the error line, I see UART is defined for COM3 by default in code and so I changed it to UART(1, 9600) which is mine. Hope that is fine.

Meanwhile, the blinky runs fine with "exec(open("PyTrinamicMicro/platforms/motionpy/examples/io/blinky.py").read())" and not working with "exec(MP.script("blinky"))".

Please check the below clips:
![Screenshot (1103)](https://user-images.githubusercontent.com/52508011/117753643-78d2ef80-b236-11eb-9fca-d3561fd1a0c7.png)
![Screenshot (1107)](https://user-images.githubusercontent.com/52508011/117754872-d405e180-b238-11eb-825a-5eee84d66e0a.png)

![Screenshot (1104)](https://user-images.githubusercontent.com/52508011/117753692-8c7e5600-b236-11eb-8025-2629902c9e3a.png)
@Lionheart1810

**Comment by Lionheart1810** [comment]
Not all example scripts are linked in the script map within the configuration class. In fact, only a few are, and the rest is up to the user. The reason for this is memory issues when all scripts are linked and used together with multiple instances of TMCL-Modules.

However, the blinky script should already be linked there correctly after commit aa7961f, which was yesterday.

**Comment by NavadeepGaneshU** [comment]
Well, okay. That helps. So, by now the hardware is successfully running micropython. But I am still trying to figure out why TMCL-IDE is not recognizing TMCM-0960-MotionPy Kit. Any troubleshoot tips?

@Lionheart1810

**Comment by Lionheart1810** [comment]
Are you running a TMCL-Slave implementation on the MotionPy?
If not, the TMCL-IDE has no chance to see it, since it is a TMCL-Master. Also, the TMCL-Slave reference implementations do not provide plenty of additional functionality by itself without any TMCL-Module attached.

There are example scripts for TMCL-Slave and TMC-Bridge.

**Comment by NavadeepGaneshU** [comment]
I didn't run the TMCL-Slave script on TMCM-0960-MotionPy Kit and was trying to get it detected in IDE. Yes, I am using  PD42-1270 stepper motor via CAN interface to the MotionPy Kit. So, I should invoke TMCL_Bridge.py, TMCL_slave.py from H:\PyTrinamicMicro? But how? 

I am looking into this manual https://www.247motioncontrol.com/media/1271/tmcl-ide_usermanual_v201.pdf and it doesn't specify and instructions about running scripts and connection. 

@Lionheart1810

**Comment by NavadeepGaneshU** [comment]
I tried to run example scripts from H:\PyTrinamicMicro\platforms\motionpy of tmcl_slave_demo, _dummy and _motionpy, but that doesn't seem good. Aren't these features mapped/enabled yet? How can users avail them to run?
![Screenshot (1109)](https://user-images.githubusercontent.com/52508011/117835608-a56a2400-b295-11eb-9455-39fbca5a3ac4.png)

@Lionheart1810

**Comment by Lionheart1810** [comment]
In your `open(...)` statement you are adding escape characters by using backslashes. Use normal slashes instead (take `GUIDE.MD` or `MotionPy` class as reference).

The TMCL-IDE does not detect non-TMCL devices. Since the MotionPy is general purpose and can be run in different modes, you have to explicitly run a TMCL-Slave on there in order to use it with external TMCL-Masters, like the TMCL-IDE.

I'd suggest running the example scripts `tmcl_slave_usb` or `tmcl_slave_uart` (if you want to additionally monitor via USB) as a starting point.

This is not documented in the TMCL-IDE docs, since its totally module dependent.
We are working on an application note for using it together with a TMCM-1270, but this has still to run through our internal process.

Still, I am wondering what your specific use case is. The reference TMCL-Slave implementations just feature few control commands to e.g. stop the application etc. To use the MotionPy itself as a TMCL-Master, terminal access is the intended way to do so.

**Comment by NavadeepGaneshU** [comment]
Oh, my bad. I corrected the backlash error now.

Yes, I tried example scripts from tmcl_slave_usb and tmcl_slave_uart too, but that doesn't seem to work for me.

>>> exec(open("PyTrinamicMicro/platforms/motionpy/examples/tmcl_slave/tmcl_slave_uart.py").read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 11, in <module>
ImportError: can't import name TMCL_Slave_Main


>>> exec(open("PyTrinamicMicro/platforms/motionpy/examples/tmcl_slave/tmcl_slave_usb.py").read())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<string>", line 43, in <module>
File "PyTrinamicMicro/connections/tmcl_host_interface.py", line 44, in receive_request
File "PyTrinamicMicro/platforms/motionpy/connections/usb_vcp_tmcl_interface.py", line 50, in _recv
v
TypeError: object with buffer protocol required

Yes, so my application/target is to connect the PyBoard to TMCL-IDE and with motor over CAN bus to monitor the health of motion and get plots of velocity, torque and loads utilizing StallGuard and CoolStep features. I was sponsored with this kit by Trinamic for RoadTesting https://www.element14.com/community/roadTests/2296/l/trinamic-tmcm-0960-motionpy-sbc-stepper-motor and having some issues in getting started.

**Comment by NavadeepGaneshU** [comment]
Okay, now I ran the script `PyTrinamicMicro/connections/tmcl_module_interface.py` and by closing Putty and trying to connect in TMCL-IDE, I see this in logs. But the development board tree has not come up below the serial port(i.e, hardware not recognized). Any luck?
![Screenshot (1110)](https://user-images.githubusercontent.com/52508011/117865055-1bc94f00-b2b3-11eb-98ce-32e82a094093.png)

@Lionheart1810

**Comment by Lionheart1810** [comment]
`PyTrinamicMicro/connections/tmcl_module_interface.py` is just the base class for `tmcl_interface`s that can be used as an interface towards a TMCL-Module (in contrast to `tmcl_host_interface` as base class towards TMCL-Masters). It makes no sense to run it as a script directly.

But you should be able to run the `tmcl_slave_usb` example to communicate with the TMCL-IDE. Keep in mind that you need to detach PuTTY after starting the script without sending any characters. Any character sent will be interpreted as part of TMCL-Command, which is not what you want, and is resulting in the error above. After detaching PuTTY, you should be able to connect via IDE.

`tmcl_slave_uart` had a bug using the wrong name for the TMCL-Slave implementation, hence the error. I just patched it. I suggest you pulling the new version.

From your use case, I see the MotionPy rather in the TMCL-Bridge role than TMCL-Slave. That way, you can bridge connections between USB on one side (with the TMCL-IDE attached) and CAN on the other (with the TMCM-1270 attached). You can then also use the callbacks to log intermitting packets and analyze and plot them externally. There are also example scripts for that.

**Comment by NavadeepGaneshU** [comment]
Oh, lit. I am getting clarity now. I didn't have much idea on how the file tree is in PyTrinamicMicro repo.

Also, https://www.trinamic.com/products/modules/details/tmcm-0960-motionpy/ has a `TMCL Firmware V1.0.hex` file, but there are no instruction on how to use it with TMCM-0960-MotionPy. Is this firmware is what interfaces with TMCL-IDE? Need to put it in SD Card?

With `tmcl_slave_usb` I am getting things up. The board is detected as unknown though.

![Screenshot (1113)](https://user-images.githubusercontent.com/52508011/117911891-29ef8d80-b2fc-11eb-8735-777039ef5131.png)

For my use case, yes, what you told is right. The MotionPy should just act as a CAN to USB bridge with TMCM-1270 being attached to the MotionPy's CAN peripheral interface. TMCM-1270 motor can also be interafced by directly using USB-CAN adapter module(like USB-TTL) I think, but here MotionPy needs to act as that convertor. 
So, I ran the CAN bridging scripts from `PyTrinamicMicro/platforms/motionpy1/examples/tmcl_bridge` and they do run sucessfully, but not detected by TMCL-IDE. 

Fixing this one thing would resolve my issue. Let me know if you have any idea, please. 

@Lionheart1810

**Comment by Lionheart1810** [comment]
I've just changed the board id for the slave examples, they should now be detected as TMCM-0960-MotionPy.

For USB to CAN run the example script `tmcl_bridge_usb_can` or `tmcl_bridge_usb_x`.
There you also need to close PuTTY without sending extra chars. The TMCM-1270 needs to be powered on via supply and properly wired up. From TMCL-IDEs perspective, the TMCM-1270 should then be detected with module id 1, and the MotionPy on module id 3.

**Comment by NavadeepGaneshU** [comment]
Cool, with the first example `tmcl_slave_usb.py`, the TMCL-IDE is detecting the module, and it's pretty much idle without the motor CAN interface(you're right!). So, trying the `tmcl_bridge_usb_can.py` and `tmcl_bridge_usb_x.py`, it does run in Putty but unable to detect either of the modules(MotionPy and Motor) in IDE. I checked if there are board specific definitions in `tmcl_bridge_usb_can.py`, but didn't find straight forward things to troubleshoot.

@Lionheart1810

**Comment by Lionheart1810** [comment]
Thats strange, because for me everything is working fine with the exact same setup.
Can you confirm the following execution order?

1. Wire up TMCM-1270 and connect it to MotionPy.
2. Turn on power supply. I did it with 20V.
3. Attach the MotionPy via USB to the PC.
4. Connect to the MotionPy via PuTTY
5. Run the `tmcl_bridge_usb_can` example.
6. Close PuTTY without any extra chars sent.
7. Open TMCL-IDE and scan for ID 1 (default) for just the TMCM-1270 or scan for ID range 1 to 3 to additionally have the MotionPy control instance.

![Screenshot_20210512_141840](https://user-images.githubusercontent.com/809956/117974297-b4041a00-b32d-11eb-9166-bea81eea4abd.png)

**Comment by NavadeepGaneshU** [comment]
Amazing! It did work now and I am getting control over the motor. Previously I was using dot 9V and now switched to 12V with which the IDE detects both the modules and all good. Thanks for the quick and friendly support. That helped a lot :)

Now I am moving on with my robotic arm design project to control position, motion, and monitor the load to extract data for further processing. And also I am gonna write a review about this kit under the element14 RoadTest review program. Thanks for helping on the way and I think this will help others too in getting started.

So, you have several Trinamic Motors and Kits to play around and tryout with :) Beauty!!!
